version: 2

sources:
  - name: rdl_ref_zone
    description: A replica of the postgres database used to power the jaffle_shop app.
    database: rdl_ref_zone
    schema: rdl_rmsprd_rms
    tables:
      - name: store__v
      - name: wh__v
      - name: item_master__v
      - name: item_loc_soh__v
      - name: ros_impact_data__v
      - name: tran_data_history
      - name: tran_data_history__ct


      

             