version: 2

sources:
  - name: secure
    database: sa_isabela_1
    schema: development
    tables:
      - name: us
  - name: resmed
    database: sa_isabela_1
    schema: development
    tables:
      - name: source_secure_customers
        tags: ['secure']
    

